/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeRouteImport } from './routes/code'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiBoardRouteImport } from './routes/api/board'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiE2eSessionRouteImport } from './routes/api/e2e/session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardRoute = ApiBoardRouteImport.update({
  id: '/api/board',
  path: '/api/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiE2eSessionRoute = ApiE2eSessionRouteImport.update({
  id: '/api/e2e/session',
  path: '/api/e2e/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/login': typeof LoginRoute
  '/api/board': typeof ApiBoardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/e2e/session': typeof ApiE2eSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/login': typeof LoginRoute
  '/api/board': typeof ApiBoardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/e2e/session': typeof ApiE2eSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/login': typeof LoginRoute
  '/api/board': typeof ApiBoardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/e2e/session': typeof ApiE2eSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/code' | '/login' | '/api/board' | '/api/auth/$' | '/api/e2e/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/code' | '/login' | '/api/board' | '/api/auth/$' | '/api/e2e/session'
  id:
    | '__root__'
    | '/'
    | '/code'
    | '/login'
    | '/api/board'
    | '/api/auth/$'
    | '/api/e2e/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeRoute: typeof CodeRoute
  LoginRoute: typeof LoginRoute
  ApiBoardRoute: typeof ApiBoardRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiE2eSessionRoute: typeof ApiE2eSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/board': {
      id: '/api/board'
      path: '/api/board'
      fullPath: '/api/board'
      preLoaderRoute: typeof ApiBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/e2e/session': {
      id: '/api/e2e/session'
      path: '/api/e2e/session'
      fullPath: '/api/e2e/session'
      preLoaderRoute: typeof ApiE2eSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeRoute: CodeRoute,
  LoginRoute: LoginRoute,
  ApiBoardRoute: ApiBoardRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiE2eSessionRoute: ApiE2eSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
