/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as CodeRouteImport } from './routes/code'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ApiBoardRouteImport } from './routes/api/board'
import { Route as ApiTelemetryRouteImport } from './routes/api/telemetry'
import { Route as ApiAttachmentsIdRouteImport } from './routes/api/attachments/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiE2eSessionRouteImport } from './routes/api/e2e/session'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardRoute = ApiBoardRouteImport.update({
  id: '/api/board',
  path: '/api/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetryRoute = ApiTelemetryRouteImport.update({
  id: '/api/telemetry',
  path: '/api/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentsIdRoute = ApiAttachmentsIdRouteImport.update({
  id: '/api/attachments/$id',
  path: '/api/attachments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiE2eSessionRoute = ApiE2eSessionRouteImport.update({
  id: '/api/e2e/session',
  path: '/api/e2e/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/code': typeof CodeRoute
  '/connections': typeof ConnectionsRoute
  '/consent': typeof ConsentRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/api/board': typeof ApiBoardRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/e2e/session': typeof ApiE2eSessionRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/code': typeof CodeRoute
  '/connections': typeof ConnectionsRoute
  '/consent': typeof ConsentRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/api/board': typeof ApiBoardRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/e2e/session': typeof ApiE2eSessionRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/code': typeof CodeRoute
  '/connections': typeof ConnectionsRoute
  '/consent': typeof ConsentRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/api/board': typeof ApiBoardRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/api/attachments/$id': typeof ApiAttachmentsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/e2e/session': typeof ApiE2eSessionRoute
  '/api/github/webhook': typeof ApiGithubWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/code'
    | '/connections'
    | '/consent'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/api/board'
    | '/api/telemetry'
    | '/api/attachments/$id'
    | '/api/auth/$'
    | '/api/billing/webhook'
    | '/api/e2e/session'
    | '/api/github/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/code'
    | '/connections'
    | '/consent'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/api/board'
    | '/api/telemetry'
    | '/api/attachments/$id'
    | '/api/auth/$'
    | '/api/billing/webhook'
    | '/api/e2e/session'
    | '/api/github/webhook'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/code'
    | '/connections'
    | '/consent'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/api/board'
    | '/api/telemetry'
    | '/api/attachments/$id'
    | '/api/auth/$'
    | '/api/billing/webhook'
    | '/api/e2e/session'
    | '/api/github/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  CodeRoute: typeof CodeRoute
  ConnectionsRoute: typeof ConnectionsRoute
  ConsentRoute: typeof ConsentRoute
  CookiesRoute: typeof CookiesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiBoardRoute: typeof ApiBoardRoute
  ApiTelemetryRoute: typeof ApiTelemetryRoute
  ApiAttachmentsIdRoute: typeof ApiAttachmentsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiE2eSessionRoute: typeof ApiE2eSessionRoute
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/board': {
      id: '/api/board'
      path: '/api/board'
      fullPath: '/api/board'
      preLoaderRoute: typeof ApiBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry': {
      id: '/api/telemetry'
      path: '/api/telemetry'
      fullPath: '/api/telemetry'
      preLoaderRoute: typeof ApiTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments/$id': {
      id: '/api/attachments/$id'
      path: '/api/attachments/$id'
      fullPath: '/api/attachments/$id'
      preLoaderRoute: typeof ApiAttachmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/e2e/session': {
      id: '/api/e2e/session'
      path: '/api/e2e/session'
      fullPath: '/api/e2e/session'
      preLoaderRoute: typeof ApiE2eSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  CodeRoute: CodeRoute,
  ConnectionsRoute: ConnectionsRoute,
  ConsentRoute: ConsentRoute,
  CookiesRoute: CookiesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ApiBoardRoute: ApiBoardRoute,
  ApiTelemetryRoute: ApiTelemetryRoute,
  ApiAttachmentsIdRoute: ApiAttachmentsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiE2eSessionRoute: ApiE2eSessionRoute,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
