/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodeRouteImport } from './routes/code'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiBoardUserIdRouteImport } from './routes/api/board.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardUserIdRoute = ApiBoardUserIdRouteImport.update({
  id: '/api/board/$userId',
  path: '/api/board/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/login': typeof LoginRoute
  '/api/board/$userId': typeof ApiBoardUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/login': typeof LoginRoute
  '/api/board/$userId': typeof ApiBoardUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/login': typeof LoginRoute
  '/api/board/$userId': typeof ApiBoardUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/code' | '/login' | '/api/board/$userId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/code' | '/login' | '/api/board/$userId'
  id: '__root__' | '/' | '/code' | '/login' | '/api/board/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeRoute: typeof CodeRoute
  LoginRoute: typeof LoginRoute
  ApiBoardUserIdRoute: typeof ApiBoardUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/board/$userId': {
      id: '/api/board/$userId'
      path: '/api/board/$userId'
      fullPath: '/api/board/$userId'
      preLoaderRoute: typeof ApiBoardUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeRoute: CodeRoute,
  LoginRoute: LoginRoute,
  ApiBoardUserIdRoute: ApiBoardUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
